<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="DTOs\Settings\**" />
    <EmbeddedResource Remove="DTOs\Settings\**" />
    <None Remove="DTOs\Settings\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Data\DA.Entities\DA.Entities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="DTOs\RequestDTO\Customer\" />
  </ItemGroup>
</Project>