<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\IN.Common\IN.Common.csproj" />
    <ProjectReference Include="..\..\Infrastructure\IN.DataAccess\IN.ORM.csproj" />
    <ProjectReference Include="..\..\Infrastructure\IN.Logging\IN.Logging.csproj" />
    <ProjectReference Include="..\DA.Entities\DA.Entities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="DAO\Settings\" />
  </ItemGroup>
</Project>