<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Exception\**" />
    <EmbeddedResource Remove="Exception\**" />
    <None Remove="Exception\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IN.Logging\IN.Logging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Exceptions\" />
  </ItemGroup>
</Project>